first_social/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'accounts'
urlpatterns = [
    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),

]

first_social/first_social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('test', views.TestPage.as_view(), name='test'),
    path('thanks', views.ThanksPage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
]

first_social/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='all'),
    path('create/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', views.DeletePost.as_view(), name='delete'),
]

first_social/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
<!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-3qFzZ2O/vz+zD0lUk+bq3/hyOQsSPFapbJmBm+RyoRZElU4okc4bNTa4EZLxNlljrL0Nnm/xXZ+MgE+dSPFX+w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<!--  medium-->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
<!--  custom css-->
    <link rel="stylesheet" href="{% static 'first_social/css/master.css'%}">

<!--  google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Noto+Sans:wght@300&family=Ubuntu&display=swap" rel="stylesheet">

    <title>Michael's social</title>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">My Website</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'groups:all' %}">Groups </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login'%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'groups:all'%}">Groups</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup'%}">SignUp</a>
            </li>
          {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container my-content ">
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'first_social/js/master.js'%}" type="text/javascript" ></script>

</body>
</html>

first_social/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Welcome to Michael's social</h1>
{% endblock %}

first_social/templates/test.html
{% extends 'base.html' %}

{% block content %}
  <h1>You are logged in</h1>
{% endblock %}

first_social/templates/thanks.html
{% extends 'base.html' %}

{% block content %}
  <h1>Thank you</h1>
{% endblock %}