first_social/first_social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('test', views.TestPage.as_view(), name='test'),
    path('thanks', views.ThanksPage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
]

first_social/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='all'),
    path('create/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', views.DeletePost.as_view(), name='delete'),
]

first_social/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

import misaka
from groups.models import Group
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='posts', null=True, blank=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username, 'pk': self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

first_social/posts/forms.py
from django import forms
from . import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

first_social/posts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, CreateView, ListView, DeleteView
from django.http import Http404
from braces.views import SelectRelatedMixin
from . import forms
from . import models
from django.contrib.auth import get_user_model
# Create your views here.
User = get_user_model()


class PostListView(SelectRelatedMixin, ListView):
    model = models.Post
    select_related = ('user', 'group')


class UserPosts(ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(
                username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, CreateView):
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        if self.object.user in self.object.group.members.iterator():
            self.object.save()
            return super().form_valid(form)
        else:
            messages.warning(self.request, message='Not a member!')
            return self.form_invalid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

first_social/posts/templates/posts/_post.html
<div class="post media">
	<h3>{{ post.message_html|safe }}</h3>
	<div class="media-body">
		<h5 class="media-heading">
			<span class="username"><a class="link-primary text-decoration-none" href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
			<time class="time"><a class="link-primary text-decoration-none" href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
			{% if post.group %}
			<span class="group-name">in <a class="link-primary text-decoration-none" href="{% url 'groups:single' slug=post.group.slug%}">{{ post.group.name }}</a></span>
			{% endif %}
		</h5>
		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-danger">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

first_social/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
	<div class="container">
		<div class="row">
			{% block pre_post%}{% endblock %}
			{% block post_content %}{% endblock %}
			{% block post_post%}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

first_social/posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}


{% block post_content %}
<h3>Are you sure you want to delete this post </h3>
<div class="posts">
    {% include 'posts/_post.html' with post=object hide_delete=True %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Confirm Delete" class="btn btn-danger">
        <a class="btn btn-info" href="{% url 'posts:single' username=user.username pk=object.pk%}">Cancel</a>
    </form>
</div>
{% endblock %}

first_social/posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}


{% block post_content %}
    <div class="col-md-8">
        {% include 'posts/_post.html' %}
    </div>
{% endblock %}

first_social/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}


{% block post_content %}
    <h1>New Post</h1>
    <form id="postForm" action="{% url 'posts:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form%}
        <button class="btn btn-primary" type="submit">Submit </button>
    </form>

{% endblock %}

first_social/posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}


{% block pre_post %}
    <div class="col-md-8">
    {% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a class="link-primary text-decoration-none" href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %}#}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a class="link-primary text-decoration-none" href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>
		</div>
	</div>

    </div>
{% endblock %}
{% block post_content %}
	<div class="col-md-8">
		{% for post in post_list %}
	  		{% include "posts/_post.html" %}
		{% endfor %}
	</div>
{% endblock %}

first_social/posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}


{% block pre_post %}
    <div class="col-md-4">
        <a class="link-primary text-decoration-none" href="{% url 'posts:for_user' username=post_user.username%}"><h1>@{{post_user.username}}</h1></a>
    </div>
{% endblock %}
{% block post_content %}
    {% for post in post_list %}
        {% include 'posts/_post.html' %}
    {% endfor %}
{% endblock %}