first_social/first_social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('test', views.TestPage.as_view(), name='test'),
    path('thanks', views.ThanksPage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
]

first_social/groups/urls.py
from django.urls import path
from . import views
app_name = 'groups'

urlpatterns = [
    path('', views.ListGroup.as_view(), name='all'),
    path('create', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug>/', views.SingleGroup.as_view(), name='single'),
    path('join/<slug>', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>', views.LeaveGroup.as_view(), name='leave'),
]

first_social/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='all'),
    path('create/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', views.DeletePost.as_view(), name='delete'),
]

first_social/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

import misaka
from django.contrib.auth import get_user_model
from django import template
# Create your models here.
User = get_user_model()
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='memberships')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')
    pass

first_social/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
from django.contrib import messages
from .models import Group, GroupMember
from django.urls import reverse
from django.views.generic import (DetailView, DeleteView, CreateView,
                                  ListView, UpdateView, RedirectView)
# Create your views here.


class CreateGroup(LoginRequiredMixin, CreateView):
    model = Group
    fields = ('name', 'description')
    template_name = 'groups/groups_form.html'


class SingleGroup(LoginRequiredMixin, DetailView):
    model = Group
    template_name = 'groups/groups_detail.html'



class ListGroup(ListView):
    model = Group
    template_name = 'groups/groups_list.html'


class JoinGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, message="Already a member")
        else:
            messages.success(self.request, message="You are now a member")

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):

        try:
            membership = GroupMember.objects.get(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            )
        except GroupMember.DoesNotExist:
            messages.warning(self.request, message="You are not in this group")
        else:
            membership.delete()
            messages.success(self.request, message="You have left the group")

        return super().get(request, *args, **kwargs)

first_social/groups/templates/groups/groups_base.html
{% extends 'base.html' %}
{% load bootstrap5 %}



{% block content %}
    <div class="container">
        <div class="row">
            {% block pregroup %}
            {% endblock%}
            {% block group_content %}
            {% endblock%}
            {% block postgroup %}
            {% endblock%}
        </div>
    </div>
{% endblock %}

first_social/groups/templates/groups/groups_detail.html
{% extends 'groups/groups_base.html' %}

{% block pregroup %}
  <h1>{{group.name}}</h1>
  <h2>Member count: {{group.members.count}}</h2>

  <div class="content">
    {% if user in group.members.all %}
      <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-danger">
        <i class="bi bi-x-circle-fill"></i>Leave</a>
    {% else %}
      <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-success">
        <span class="bi bi-person-plus-fill"></span>Join</a>
    {% endif %}
  </div>
{% endblock %}

{% block group_content %}
  <div class="col-md-8">
    {% if group.posts.count == 0%}
      <h2>No post for this group</h2>
    {% else %}
      {% for post in group.posts.all %}
        {% include 'posts/_post.html'%}
      {% endfor %}

    {% endif %}

  </div>

{% endblock %}

first_social/groups/templates/groups/groups_form.html
{% extends 'groups/groups_base.html' %}
{% load bootstrap5 %}


{% block group_content %}
  <h3>Create a new group </h3>
  <form action="{% url 'groups:create' %}" method="post" id="groupform">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit">Create</button>
  </form>
{% endblock %}

first_social/groups/templates/groups/groups_list.html
{% extends 'groups/groups_base.html' %}

{% block pregroup %}
  <div class="col-md-4">
    <div class="content">
      {% if user.is_authenticated %}
        <h1> Welcome back
          <a class="link-primary text-decoration-none" href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
        </h1>
      {% endif%}
      <h2>Groups</h2>
      <p>welcome to the groups page</p>
    </div>
    {% if user.is_authenticated %}
      <a href="{% url 'groups:create' %}" class="btn btn-primary">
        <i class="bi bi-people"></i>Create Group
      </a>
    {% endif %}
  </div>
{% endblock%}

{% block group_content %}
  <div class="col-md-8">
    <div class="list-group">
      {% for group in object_list %}
        <a class="list-group-item " href="{% url 'groups:single' slug=group.slug %}">
            <h3 class="title list-group-item-heading">{{group.name}}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge bg-primary">{{group.members.count}}</span> member{{ group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge bg-primary">{{group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}